### ISSUE TITLE
Anchor link is not working

### ISSUE THREAD

**Issue by remibetin** [w3c/wai-InvolveUsersEval#12]
In the Drawing Conclusions and Reporting section, the anchor link "#caution" (see the [Caution](#caution) above) is not working.

**Comment by remibetin** [comment]
@slhenry If it is easier for you, I can create a PR to fix this. Let me know 😉

**Comment by shawna-slh** [comment]
Thanks @remibetin . I finally got to it.

Yes, for the future, I welcome PRs for fixes such as this!

I also fixed two double brackets and one word: https://github.com/w3c/wai-InvolveUsersEval/commit/9fb9f4171103fdb0ce78ada9fec959ea28b4b81b#diff-a4f40b84fbcf1a7939d596dca4939bbae6e56c05ad06a62b719b42693a9baf07

**Would you update those in the French translation**? :-)

**Comment by remibetin** [comment]
> Thanks @remibetin . I finally got to it.
> 
> Yes, for the future, I welcome PRs for fixes such as this!
> 
> I also fixed two double brackets and one word: [9fb9f41#diff-a4f40b84fbcf1a7939d596dca4939bbae6e56c05ad06a62b719b42693a9baf07](https://github.com/w3c/wai-InvolveUsersEval/commit/9fb9f4171103fdb0ce78ada9fec959ea28b4b81b#diff-a4f40b84fbcf1a7939d596dca4939bbae6e56c05ad06a62b719b42693a9baf07)
> 
> **Would you update those in the French translation**? :-)

Yes : I'm on it !
